### ISSUE TITLE
compatible key switches

### ISSUE THREAD

**Issue by stuart-warren** [FrameworkComputer/InputModules#2]
I'm very excited by this project, especially the usb support.

If we were to build homebrew input modules that are more ergonomic what key-switches would even fit under the screen?

Kailh choc switches look like they may not, and I don't believe cherry mx ultra low profile are even available to the public in small quantities.

Ideally I'd like to build (assuming you won't provide) an input module in a similar style to 
* https://golem.hu/board/Choctopus44-439.html
* https://golem.hu/board/Zephirum-440.html

**Comment by carcinization** [comment]
the question i have is more "what parts are going to be used in the keyboard it deploys with?" because if they open up that information, that will make it easier for us to just remix that design without worrying about sourcing new parts to fit and reinventing the wheel. obviously the keyboard it deploys with probably won't be mechanical, but I figure it's more important to have flexibility of layout than having the actual mechanical switches. plus then we could re-use the keycaps from the original keyboard module!

**Comment by alaricljs** [comment]
By my read the absolute total height counting all the parts in the area for key switches is 3.65mm.

The total height of a Cherry MX ULP switch without keycap is 3.5mm.  You're not going to be able to mount that to a board (it's SMD mount) and add keycaps inside .15mm.  I don't believe there is a truly DIY possibility here, maybe a small-scale kickstarter from an experienced manufacturer in laptop membrane keyboards.

**Comment by carcinization** [comment]
i agree that there's no room for switches, but i disagree that there's no DIY possibility. i think we could probably make membrane work in DIY. i mean there's topre DIY... it should certainly be possible. keyboards are one of the easiest things to hack together i think because it's so electrically simple. i just hope we can find out about the parts used in the original keyboard so we can try to source similar materials.

**Comment by eclecticc** [comment]
Closing this since it isn't addressable within this repository.  There is ongoing discussion around keyswitches in the Framework Community: https://community.frame.work/t/input-module-keyboard-switches/28294/8
